// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VegasBackend.DbContex;

#nullable disable

namespace VegasBackend.Migrations
{
    [DbContext(typeof(AppDbContex))]
    [Migration("20250812162720_FinallyAddedPlayers")]
    partial class FinallyAddedPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VegasBackend.ServerLogic.GameDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoardJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MadeMovesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<string>("Player1Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Player2Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("PlayerId1")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("VegasBackend.ServerLogic.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("VegasBackend.ServerLogic.GameDb", b =>
                {
                    b.HasOne("VegasBackend.ServerLogic.Player", null)
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("PlayerId");

                    b.HasOne("VegasBackend.ServerLogic.Player", null)
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("PlayerId1");
                });

            modelBuilder.Entity("VegasBackend.ServerLogic.Player", b =>
                {
                    b.Navigation("GamesAsPlayer1");

                    b.Navigation("GamesAsPlayer2");
                });
#pragma warning restore 612, 618
        }
    }
}
