@VegasBackend_HostAddress = http://localhost:5098

GET {{VegasBackend_HostAddress}}/initializeAndGetBoard
Accept: application/json

###

POST {{VegasBackend_HostAddress}}/CreateAndGetBoard
Content-Type: application/json
Accept: application/json
{
  "Player1Id": "test1",
  "Player2Id": "test2"
}


